server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            
              
      routes:
        - id: user-registration-service
          uri: lb://user-registration-service
          predicates:
            - Path=/user/**
        - id: security-service
          uri: lb://security-registration-service
          predicates:
            - Path=/**

eureka:
  instance:
    hostname: localhost
      